import mongoose from 'mongoose';

const { Schema } = mongoose;

const foodItemSchema = new Schema({
    name: {
        type: String,
        required: true,
        trim: true,
    },
    quantity: {
        type: Number,
        required: true,
        min: 0,
    },
    unit: {
        type: String,
        required: true,
        trim: true,
    },
    calories: {
        type: Number,
        required: true,
        min: 0,
    },
    protein: {
        type: Number,
        default: 0,
        min: 0,
    },
    carbs: {
        type: Number,
        default: 0,
        min: 0,
    },
    fats: {
        type: Number,
        default: 0,
        min: 0,
    },
}, { _id: false });

const mealSchema = new Schema({
    mealType: {
        type: String,
        enum: ['breakfast', 'lunch', 'dinner', 'snack', 'cheat-day'],
        required: true,
    },
    items: {
        type: [foodItemSchema],
        required: true,
    },
    totalCalories: {
        type: Number,
        required: true,
    },
    notes: {
        type: String,
        trim: true,
    },
}, { _id: false });

const dietPlanSchema = new Schema({
    userId: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    profileId: {
        type: Schema.Types.ObjectId,
        ref: 'Profile',
        required: true,
    },
    // Date for this specific daily plan (normalized to midnight for calendar day uniqueness)
    date: {
        type: Date,
        required: true,
    },
    // Daily meal plan (breakfast, lunch, dinner, snacks, cheat-day)
    meals: {
        type: [mealSchema],
        required: true,
    },
    // Daily targets
    dailyCalories: {
        type: Number,
        required: true,
    },
    dailyProtein: {
        type: Number,
        default: 0,
    },
    dailyCarbs: {
        type: Number,
        default: 0,
    },
    dailyFats: {
        type: Number,
        default: 0,
    },
    // Generated by AI
    generatedByAI: {
        type: Boolean,
        default: true,
    },
}, {
    timestamps: true,
});

// Pre-save hook to normalize date to midnight (00:00:00.000) for calendar day uniqueness
dietPlanSchema.pre('save', function (next) {
    if (this.isModified('date') && this.date) {
        // Normalize date to midnight UTC to ensure calendar day uniqueness
        const normalizedDate = new Date(this.date);
        normalizedDate.setUTCHours(0, 0, 0, 0);
        normalizedDate.setUTCMilliseconds(0);
        this.date = normalizedDate;
    }
    next();
});

// Indexes
dietPlanSchema.index({ userId: 1, date: -1 });
dietPlanSchema.index({ userId: 1, date: 1 }, { unique: true }); // One plan per user per calendar day

const DietPlan = mongoose.models.DietPlan || mongoose.model('DietPlan', dietPlanSchema, 'diet_plans');

export default DietPlan;

